- app/build.gradle
- build.gradle
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- [Renovate의 원활한 활용](https://docs.renovatebot.com/java/)과 조금 더 편안한 버전관리를 위해 Gradle에서 오피셜하게 제공하는 Version Catalog 기능을 활용해볼까 합니다.
**Reference**
- [링크](https://docs.gradle.org/current/userguide/platforms.html)
> [feature/version catalog] Gradle Version Catalog 적용

- app/src/main/java/org/sopt/official/data/service/attendance/AttendanceService.kt
- app/src/main/java/org/sopt/official/di/NetModule.kt
- app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
- app/src/main/java/org/sopt/official/feature/attendance/adapter/AttendanceAdapter.kt
- app/src/main/java/org/sopt/official/feature/attendance/adapter/SummaryViewHolder.kt
- app/src/main/res/anim/anim_rotation.xml
- app/src/main/res/layout/activity_attendance.xml
- app/src/main/res/layout/item_attendance_history_log.xml
[운영서비스] 출석 점수 조회 QA 시 나왔던 이슈들을 해결했습니다.
- '참여' 태그의 행사 참여가 0회일 때에도 참여 태그 행사의 참석 횟수를 보여줍니다.
- Retrofit baseUrl을 Build Type에 따라 개발 서버, 실 서버 다르게 연결합니다.
- 디자인 측에서 제안한대로 TextView의 양쪽 마진값을 조정했습니다.
- 서버 측에서 수정한 EndPoint를 반영했습니다.
- 새로고침 아이콘 클릭 시 아이콘을 회전시킵니다.
- 새로고침 시 RecyclerView의 다른 position이 깜빡이는 오류를 발견해 임시조치 해두었습니다. 추후 리프레시 기간을 활용해 정식으로 조치하도록 하겠습니다.
> [운영서비스] 출석 점수 조회 QA 반영

- app/build.gradle.kts
- app/src/test/java/org/sopt/official/JsonObjectTest.kt
- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/JUnit5Plugin.kt
- build.gradle.kts
- gradle/libs.versions.toml
- [Test를 JUnit5로 작성하기](https://modelmaker.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-Truth-with-JUnit5)
> [feature/junit5-configuration] 테스트 라이브러리 JUnit5로 교체

- app/src/main/java/org/sopt/official/data/persistence/SoptDataStore.kt
> [feature/nunu/retry-make-shared-preference] SharedPreference 초기화 시 앱 강제 종료되는 이슈 의심 되는 부분 수정

- app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
- app/src/main/java/org/sopt/official/util/GenerationExt.kt
- app/src/main/java/org/sopt/official/util/TimeExt.kt
- app/src/test/java/org/sopt/official/JsonObjectTest.kt
- app/src/test/java/org/sopt/official/KotlinxDateTimeTest.kt
각 레벨별로 커밋을 나누어 놓았습니다. 확인해주시면 감사하겠습니다.
> [Feature/kotlinx-datetime]: #204 java-time to kotlinx-datetime migration 

- app/src/main/java/org/sopt/official/di/NetModule.kt
디버그 환경이 아닐 경우에는 loggingInterceptor의 level을 HttpLoggingInterceptor.Level.NONE으로 설정하였습니다.
확인해주시면 감사하겠습니다 !
> [Fix/LoggingInterceptor]: #213 loggingInterceptor-leak

- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
뷰모델이 생성될 때마다 init 블록이 실행되므로, onSubmit() 함수에만 적용시키는 의도에는 비효율적일 수 있습니다. 하지만 다른 함수들에도 throttle 의 로직을 적용시키면 좋을 것 같아 init 블록을 통해 submit의 SharedFlow 상태를 변경시켰습니다.
> [Feature/throttle-click] : #239 add throttle click 

- app/build.gradle.kts
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidHiltPlugin.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/di/ConfigModule.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/di/ConstantModule.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/di/constant/Constant.kt
- gradle/libs.versions.toml
> [feature/hilt-ksp] Apply ksp on hilt

- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampIconButton.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerItem.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerList.kt
> [feature/soptamp-generation-ranking] 기수별 랭킹 UI 구현

- build-logic/convention/build.gradle.kts
- add kotlin tool chain 
`./gradlew spotlessApply`를 했는데 아래처럼 되네요... 왜그럴까요?
앱 실행은 잘 됩니다!
> [featuer/soptamp-toolcahin] add Kotlin jvmToolchain

- build-logic/convention/build.gradle.kts
- feature/soptamp/build.gradle.kts
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankColor.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankListItem.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankNumber.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingBar.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerItem.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/PartRankModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingState.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingViewModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingState.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
- gradle/libs.versions.toml
closed #637 
https://github.com/sopt-makers/sopt-android/assets/52882799/73e0b257-ff74-4366-b432-349bf0c2f4f5
통짜 PR 죄송합니다... 하다가 잘 되길래 신나서 많이 해버렸어요...
api연결 제외한 부분 전부 구현했습니다!
파트별 랭킹부분은 현재 api 연결이 안되어있어 더미데이터를 넣어서 영상 찍은 후 수정했습니다.
> [feature/soptamp part ranking] Server 제외 구현 완료

- build-logic/convention/build.gradle.kts
- feature/mypage/src/main/java/org/sopt/official/feature/mypage/mypage/MyPageActivity.kt
- feature/mypage/src/main/java/org/sopt/official/feature/mypage/web/WebUrlConstant.kt
- feature/mypage/src/main/res/layout/activity_my_page.xml
https://github.com/sopt-makers/sopt-android/assets/52882799/f53c861c-e202-4d80-9ddc-36645075e3bd
- 터치영역이 아이콘만 잡혀있어 사용하기 불편함을 느껴서 layout 전체로 변경했습니다
- `알림 설정하기`의 경우 이미 layout으로 되어있어 `서비스 이용방침`에도 적용해봤습니다
- layout으로 바꾸는것에 반대의견 없으시면 나머지 버튼들도 전부 layout으로 수정하도록 하겠습니다! 선생님들 의견 듣고 수정하려고 `서비스 이용방침`만 수정했습니다 :)
> [hotfix/contact with kakao] 문의하기 링크 google -> kakao

- app/src/main/java/org/sopt/official/config/messaging/ServiceLifecycleDispatcher.kt
- app/src/main/java/org/sopt/official/config/messaging/SoptFirebaseMessagingService.kt
- [LifecycleService](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-service/src/main/java/androidx/lifecycle/LifecycleService.kt?q=file:androidx%2Flifecycle%2FLifecycleService.kt%20class:androidx.lifecycle.LifecycleService)
- [ServiceLifecycleDispatcher](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-service/src/main/java/androidx/lifecycle/ServiceLifecycleDispatcher.kt?q=ServiceLifecycleDispatcher)
> [feature/apply-lifecycle-service] Service에 Lifecycle 적용하기

- core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
**AS-IS : 백 버튼을 누르면 재정의되어있지 않기에 액티비티 종료**
https://github.com/sopt-makers/sopt-android/assets/108331578/638549fd-15b3-4417-867f-02e6a752fd25
**TO-BE : 백 버튼을 누르면 웹 뷰 내에서 뒤로 이동하다가 액티비티 종료**
https://github.com/sopt-makers/sopt-android/assets/108331578/a260e4b8-1d74-43f1-8a41-27a930f78a1c
```kotlin
private fun handleOnBackPressed() {
onBackPressedDispatcher.addCallback(owner = this) {
if (binding.webView.canGoBack()) {
binding.webView.goBack()
} else {
if (!isFinishing) finish()
}
}
}
```
원래는 `if (!isFinishing) finish()` 대신 `onBackPressedDispatcher.onBackPressed()` 를 사용하려고 했으나,
그렇게 되면 add한 Callback이 다시 실행되며 무한루프를 돌게 되는 것 같습니다.
현재는 크리티컬한 이슈가 없지만, 시스템의 기존 백 버튼 로직을 사용하지 못하는게 아쉽네요.. 해결법 아시는 분 계실까요 ??
close #664
> feat: handle OnBackPressed

- app/src/main/java/org/sopt/official/feature/notification/NotificationDetailActivity.kt
- data/soptamp/src/main/java/org/sopt/official/data/soptamp/di/DataModule.kt
- data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/model/response/S3URLResponse.kt
- data/soptamp/src/main/java/org/sopt/official/data/soptamp/repository/ImageUploaderRepositoryImpl.kt
- data/soptamp/src/main/java/org/sopt/official/data/soptamp/repository/StampRepositoryImpl.kt
- domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/fake/FakeImageUploaderRepository.kt
- domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/fake/FakeStampRepository.kt
- domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/model/ImageUploadUrl.kt
- domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/repository/ImageUploaderRepository.kt
- domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/repository/StampRepository.kt
- feature/soptamp/build.gradle.kts
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
closed #695  
- 기존 구조에서는 Screen(presentation layer)에서 Request Body를 만들어서 Service(data layer)에 넘겨주는 방식이었습니다. 
- 이 구조를 유지하기 위해서는 Repository(domain layer)에 Request Body를 넘겨줘야하는데 이는 Domain Layer에 retrofit관련 의존성을 추가해줘야 했습니다.
- 이를 해결하기 위해 Uri를 String으로 넘겨주고, RepositoryImpl에서 context를 활용해 RequestBody로 변환해 통신을 하도록 하였습니다.
- 추가적으로 Image관련된 부분은 하나의 Repository에서 관리하는게 맞다고 생각되어 기존 soptampRepository에 있던 함수 하나를 ImageUploaderRepository에 옮겨주었습니다!
- Domain에 존재하는 네이밍은 S3, Remote와 관련이 없도록 종속성을 제거한 네이밍으로 수정했습니다 :)
- 근데 모듈 그래프를 만들어서 같이 올리고 싶었는데 혹시 어떻게 하나요...?
> [feature/reference module] feature/soptamp에서 data/soptamp 직접 참조 수정

- README.md
> [feature/fix_readme] README.md에서 온보딩 내용 제거

- core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
- 웹뷰의 WebChromeClient를 통해서 사진 데이터를 전달해야 웹으로 전달 가능한데 이 기능이 미구현되어 있었음
- https://sopt-makers.slack.com/archives/C042T81PW80/p1724336627505209?thread_ts=1724076848.104409&cid=C042T81PW80
> [feature/webview-image-upload] WebView의 FileChooser로 이미지 웹으로 전달 기능 구현

- baselineprofile/build.gradle.kts
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
- gradle/libs.versions.toml
- Bump targetSdk, minSdk to 35, 30
https://github.com/user-attachments/assets/1dd1dbc8-faad-4092-9450-0e9b65a1bc13
> Bump targetSdk to 35, minSdk to 30

- app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
- core/analytics/build.gradle.kts
- core/analytics/src/main/java/org/sopt/official/analytics/Tracker.kt
- core/analytics/src/main/java/org/sopt/official/analytics/TrackerModule.kt
- core/analytics/src/main/java/org/sopt/official/analytics/TrackerType.kt
- core/analytics/src/main/java/org/sopt/official/analytics/compose/CompositionLocal.kt
- core/analytics/src/main/java/org/sopt/official/analytics/compose/LocalTracker.kt
- core/analytics/src/main/java/org/sopt/official/analytics/impl/AmplitudeTracker.kt
- core/analytics/src/main/java/org/sopt/official/analytics/impl/FakeTracker.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/FortuneActivity.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/FoundationScreen.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/component/FortuneTopBar.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneAmulet/FortuneAmuletScreen.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/FortuneDetailRoute.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/home/HomeScreen.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationActivity.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingActivity.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/SoptampActivity.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingScreen.kt
> [feature/#1009] AmplitudeTracker 추상화하여 Preview에 Fake 넣을 수 있게 수정

- app/src/main/java/org/sopt/official/data/AttendanceMapper.kt
- app/src/main/java/org/sopt/official/data/repository/attendance/DefaultAttendanceRepository.kt
- app/src/main/java/org/sopt/official/di/attendance/AttendanceBindsModule.kt
- app/src/main/java/org/sopt/official/domain/entity/attendance/Attendance.kt
- app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceInfo.kt
- app/src/main/java/org/sopt/official/domain/entity/attendance/ConfirmAttendanceCodeResult.kt
- app/src/main/java/org/sopt/official/domain/entity/attendance/FetchAttendanceCurrentRoundResult.kt
- app/src/main/java/org/sopt/official/domain/repository/attendance/NewAttendanceRepository.kt
- app/src/main/java/org/sopt/official/feature/attendance/AttendanceMapper.kt
- app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceCodeDialog.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceCodeDialog.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryCard.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryUserInfoCard.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceProgressBar.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/FinalAttendanceCard.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/MidtermAttendanceCard.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/TodayAttendanceCard.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceAction.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceDayType.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceUiState.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/FinalAttendance.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/MidtermAttendance.kt
- app/src/test/java/org/sopt/official/FinalAttendanceTest.kt
출석 정보를 가져오는 API를 연결하고 도메인으로 전환, Ui에 반영까지 작업하였습니다.
추후 세션을 만들어서 테스트 해보고 수정 필요하면 수정해서 다시 올리겠슴다
> 출석 정보 가져오기 구현

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/App.kt
- app/src/release/generated/baselineProfiles/baseline-prof.txt
- app/src/release/generated/baselineProfiles/startup-prof.txt
- core/webview/build.gradle.kts
- core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
- gradle/libs.versions.toml
- settings.gradle.kts
> [feature/#946] WebView에 사진 다운로드 기능 추가

- data/home/src/main/java/org/sopt/official/data/home/mapper/HomeMapper.kt
- data/home/src/main/java/org/sopt/official/data/home/remote/response/HomeLatestPostsResponseDto.kt
- data/home/src/main/java/org/sopt/official/data/home/remote/response/HomePopularPostsResponseDto.kt
- domain/home/src/main/java/org/sopt/official/domain/home/model/LatestPost.kt
- domain/home/src/main/java/org/sopt/official/domain/home/model/PopularPost.kt
- feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
- feature/home/src/main/java/org/sopt/official/feature/home/component/HomeLatestNewsSection.kt
- feature/home/src/main/java/org/sopt/official/feature/home/component/HomePlaygroundPost.kt
- feature/home/src/main/java/org/sopt/official/feature/home/component/HomePopularNewsSection.kt
- feature/home/src/main/java/org/sopt/official/feature/home/mapper/HomeModelMapper.kt
- feature/home/src/main/java/org/sopt/official/feature/home/model/HomeUiState.kt
- feature/home/src/main/java/org/sopt/official/feature/home/navigation/HomeNavigation.kt
- feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
익명이 아닌 글들만 이동하도록 만들었어요
dev 플그가 로그인이 잘 안되네요..? 그래서 테스트를 제대로 해보진 못했지만,, 플그로 이동하는 것까진 확인했어요!
> [FEAT/#1277] 홈 플그영역에서 프로필 이동 기능 구현
