- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/App.kt
- app/src/main/java/org/sopt/official/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- gradle/libs.versions.toml
> [feature/flipper_config] Flipper 설정

- app/build.gradle
- gradle.properties
> [feature/gradle_config_change] Gradle 환경변수 및 Release 옵션 적용

- app/build.gradle
- app/src/main/java/org/sopt/official/MainActivity.kt
- gradle/libs.versions.toml
> [feature/compose_configure] Compose 설정

- app/build.gradle
- app/src/main/java/org/sopt/official/App.kt
- build.gradle
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
> [feature/hilt-config] Hilt Config

- app/build.gradle
- app/src/main/java/org/sopt/official/MainActivity.kt
- build.gradle
- gradle/libs.versions.toml
> [feature/crashlytics-register] Firebase + Crashlytics 설정

- app/src/main/java/org/sopt/official/style/Color.kt
- app/src/main/java/org/sopt/official/style/Theme.kt
- app/src/main/java/org/sopt/official/style/Type.kt
> [feature/theme-config-compose] Compose 테마/스타일링 설정

- app/build.gradle
- app/src/main/java/org/sopt/official/di/UpdateModule.kt
- gradle/libs.versions.toml
> [feature/fix-build-error] 의존성 주입 + Compose Version 관련 에러 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/feature/splash/SplashActivity.kt
- app/src/main/java/org/sopt/official/feature/splash/SplashScreen.kt
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/themes.xml
- gradle/libs.versions.toml
> [feature/splash-screen] Splash 화면 구현

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/config/TimberInitializer.kt
- gradle/libs.versions.toml
> [feature/plant-timber] Timber 심기

- .github/workflows/develop_PR_builder.yml
- .github/workflows/develop_merge_builder.yml
> [Feat/github-action-setting] github action 세팅

- app/src/main/java/org/sopt/official/feature/common/NoticeItem.kt
- app/src/main/java/org/sopt/official/feature/notice/NoticeScreen.kt
- app/src/main/java/org/sopt/official/feature/notice/model/NoticeItemModel.kt
- app/src/main/res/drawable/icon_new.xml
ref [[UI] 공지 Item](https://www.notion.so/parangjy/UI-Item-40307c425a9543dcb51380b886b252d1)
> [Feature/UI notice] 공지 리스트 아이템 UI 구현

- app/src/main/java/org/sopt/official/designsystem/components/TopBarIconButton.kt
- app/src/main/java/org/sopt/official/designsystem/style/Color.kt
- app/src/main/java/org/sopt/official/designsystem/style/Theme.kt
- app/src/main/java/org/sopt/official/designsystem/style/Type.kt
- app/src/main/java/org/sopt/official/feature/auth/EmailInputScreen.kt
- app/src/main/java/org/sopt/official/feature/common/NoticeItem.kt
- app/src/main/java/org/sopt/official/feature/notice/components/NoticeItem.kt
- app/src/main/java/org/sopt/official/feature/splash/SplashScreen.kt
> [Hotfix/package] 패키지 구조 변경

- app/src/main/java/org/sopt/official/designsystem/style/Color.kt
- app/src/main/java/org/sopt/official/designsystem/style/Theme.kt
- app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
- app/src/main/java/org/sopt/official/feature/auth/EmailInputScreen.kt
- gradle/libs.versions.toml
> [feature/email-input] Email 인증 화면 제작

- app/src/main/java/org/sopt/official/feature/auth/EmailInputScreen.kt
- app/src/main/java/org/sopt/official/feature/auth/component/AuthHeader.kt
- app/src/main/java/org/sopt/official/feature/auth/component/EmailSendScreen.kt
> [feature/certificate] 이메일 인증 완료 화면 구현하기

- .github/workflows/develop_merge_builder.yml
- app/src/main/java/org/sopt/official/config/navigation/NavHosts.kt
- app/src/main/java/org/sopt/official/feature/auth/component/AuthHeader.kt
- app/src/main/java/org/sopt/official/feature/auth/component/EmailSendScreen.kt
- app/src/main/java/org/sopt/official/feature/setting/SettingScreen.kt
- app/src/main/java/org/sopt/official/feature/setting/SettingViewModel.kt
- app/src/main/java/org/sopt/official/feature/setting/component/MenuItem.kt
- app/src/main/java/org/sopt/official/feature/setting/model/SettingItem.kt
> [feature/setting-ui] 설정화면 구현

- app/src/main/java/org/sopt/official/designsystem/components/CheckBox.kt
- app/src/main/java/org/sopt/official/domain/entity/Part.kt
- app/src/main/java/org/sopt/official/feature/setting/PushAlarmConfigViewModel.kt
- app/src/main/java/org/sopt/official/feature/setting/PushAlarmScreen.kt
- app/src/main/java/org/sopt/official/feature/setting/model/PushSelectItem.kt
- app/src/main/res/drawable/ic_check.xml
- gradle.properties
> [feature/push-alarm-config] 푸시알람 설정화면 구현

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/data/model/RequestAuthEmail.kt
- app/src/main/java/org/sopt/official/data/model/ResponseAuthEmail.kt
- app/src/main/java/org/sopt/official/data/persistence/SoptDataStore.kt
- app/src/main/java/org/sopt/official/data/repository/AuthRepositoryImpl.kt
- app/src/main/java/org/sopt/official/data/service/AuthService.kt
- app/src/main/java/org/sopt/official/di/AuthModule.kt
- app/src/main/java/org/sopt/official/domain/repository/AuthRepository.kt
- app/src/main/java/org/sopt/official/domain/usecase/AuthenticateEmailUseCase.kt
- app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
- app/src/main/java/org/sopt/official/feature/auth/EmailInputScreen.kt
- app/src/main/java/org/sopt/official/feature/auth/model/EmailAuthenticationState.kt
- app/src/main/java/org/sopt/official/feature/notice/NoticeScreen.kt
- app/src/main/java/org/sopt/official/feature/splash/SplashScreen.kt
- app/src/main/java/org/sopt/official/feature/splash/SplashViewModel.kt
- gradle/libs.versions.toml
- secrets.defaults.properties
> [feature/auth-service] 이메일 인증 과정 서버통신

- app/build.gradle
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
> :arrow_up: bump dependencies

- app/build.gradle
- app/src/main/java/org/sopt/official/App.kt
- gradle/libs.versions.toml
> [feature/use-mavericks] Mavericks(MVI Library) 사용하기

- .gitignore
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/MainActivity.kt
- app/src/main/java/org/sopt/official/config/messaging/SoptFirebaseMessagingService.kt
- app/src/main/res/values/strings.xml
- build.gradle.kts
- gradle/libs.versions.toml
- close #117 
- FCM 토큰을 가져올 때 [coroutine을 활용하여 가져올 수 있게](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-play-services/) 해봤습니다.
- 아직 토큰 등록 서버 API가 없어서 모든 로직은 TODO와 주석으로 처리했습니다.
> [feature/#117] FCM 설정

- app/build.gradle.kts
- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidApplicationPlugin.kt
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidFeaturePlugin.kt
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidHiltPlugin.kt
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/AndroidKotlinPlugin.kt
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/KotlinSerializationPlugin.kt
- build-logic/gradle.properties
- build-logic/gradle/wrapper/gradle-wrapper.properties
- build-logic/settings.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
> [feature/convention-plugins] Project에 Custom Gradle Plugin 달기

- app/src/main/res/values/themes.xml
- app/src/main/res/values/type.xml
> :lipstick: Theme, type file update

- app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
- app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
- app/src/main/java/org/sopt/official/util/Intent.kt
- app/src/main/java/org/sopt/official/util/Resource.kt
- app/src/main/java/org/sopt/official/util/coroutine/FlowExt.kt
- app/src/main/res/layout/activity_sopt_main.xml
- app/src/main/res/layout/item_main_content_member_header.xml
- app/src/main/res/values/strings.xml
> 코드 리팩토링 - user state 가져오는 부분과 collect

- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/mission/MissionComponent.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/domain/model/OtherMission.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsState.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsViewModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/UserMissionListScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/model/MissionListUiModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/model/MissionNavArgs.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/model/MissionUiModel.kt
> 솝탬프에서 상대 미션 리스트 안보이던 문제 해결

- app/src/main/res/values/type.xml
> Type system: fontweight -> textFontWeight

- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceState.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/DialogState.kt
- app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/data/error/ErrorData.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/domain/error/Error.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/MissionsState.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingState.kt
- Kotlin 1.9.0 기준 object를 [data object](https://kotlinlang.org/docs/object-declarations.html#data-objects)로 변경을 권고하고 있어서 리팩토링
> [feature/object-to-data-object] Refactor object to data object

- .gitignore
- app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
- app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerList.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankerModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankersUiModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankingListUiModel.kt
- Pair, Tirple을 각각에 맞는 Data Class로 전환
> [김다혜] Pair, Triple -> Data Class 전환

- app/src/main/AndroidManifest.xml
> Manifest에 AuthCodeHandlerActivity 추가

- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
> Add firebase app distribution

- app/src/main/AndroidManifest.xml
- feature/auth/src/main/java/org/sopt/official/auth/PlaygroundAuth.kt
> [feature/customtab-issue-fix] Custom Tab issue fix

- app/src/main/java/org/sopt/official/data/service/attendance/MockAttendanceService.kt
- app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceButtonType.kt
- app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
- app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
> 운영 서비스 - 출석 리팩토링

- feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/api/RankService.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/data/remote/source/RemoteRankingDataSource.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/data/repository/RemoteRankingRepository.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/data/source/RankingDataSource.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampFloatingButton.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/domain/model/Rank.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/domain/repository/RankingRepository.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingScreen.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingViewModel.kt
> [feature/fix-soptamp] SOPTAMP 버튼 두짝 달리게 하기

- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
> apply clipToBounds

- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampSegmentedFloatingButton.kt
> [bug/soptamp_design] 솝템프 랭킹 플로팅 버튼 디자인 수정

- app/src/main/java/org/sopt/official/data/authenticator/SoptAuthenticator.kt
- app/src/main/java/org/sopt/official/data/repository/AuthRepositoryImpl.kt
- app/src/main/java/org/sopt/official/di/AuthModule.kt
- app/src/main/java/org/sopt/official/di/HomeModule.kt
- app/src/main/java/org/sopt/official/di/NetModule.kt
- app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
- app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
- core/common/src/main/java/org/sopt/official/common/di/Qualifiers.kt
- feature/auth/build.gradle.kts
- feature/auth/src/main/java/org/sopt/official/auth/data/RemotePlaygroundAuthDatasource.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/di/RemoteModule.kt
> [feature/refresh-token] 토큰 자동 갱신 로직 추가 및 자동 로그인 기능 추가

- app/src/main/java/org/sopt/official/data/repository/AuthRepositoryImpl.kt
- app/src/main/java/org/sopt/official/data/source/api/auth/LocalAuthDataSource.kt
- app/src/main/java/org/sopt/official/data/source/api/auth/RemoteAuthDataSource.kt
- app/src/main/java/org/sopt/official/data/source/impl/DefaultLocalAuthDataSource.kt
- app/src/main/java/org/sopt/official/data/source/impl/DefaultRemoteAuthDataSource.kt
- app/src/main/java/org/sopt/official/di/AuthModule.kt
- app/src/main/java/org/sopt/official/domain/repository/AuthRepository.kt
- app/src/main/java/org/sopt/official/feature/home/HomeViewModel.kt
- app/src/main/java/org/sopt/official/feature/mypage/MyPageViewModel.kt
> [feature/fix-dependencies] 뷰모델/도메인단 코드 리팩토링

- app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
> Home 화면 유일하게 띄워놓게 만들기

- core/webview/build.gradle.kts
- core/webview/src/main/AndroidManifest.xml
- core/webview/src/main/java/org/sopt/official/webview/di/SoptWebViewEntryPoint.kt
- core/webview/src/main/java/org/sopt/official/webview/view/SoptWebView.kt
- core/webview/src/main/java/org/sopt/official/webview/view/SoptWebViewClient.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Color.kt
> Apply spotless

- gradle/libs.versions.toml
> change version reference

- README.md
- scripts/fecth_script.sh
- 3기 개발자들이 초기 개발하는데 들이는 노력이 너무 많았던 것이 생각나서 초기 설정을 빠르고 쉽게 끝내기 위해 스크립트화
- 이를 위한 온보딩 문서를 README에 작성
> [feature/onboarding-configuration-helper] 신규 개발자 초기 설정 도와주는 스크립트 제작 및 온보딩 문서 README에 추가

- app/build.gradle.kts
- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/KotlinJvmPlugin.kt
- buildSrc/build.gradle.kts
- buildSrc/gradle.properties
- buildSrc/settings.gradle.kts
- buildSrc/src/main/kotlin/sopt.kt
- core/analytics/build.gradle.kts
- core/auth/build.gradle.kts
- core/authimpl/build.gradle.kts
- core/common/build.gradle.kts
- core/designsystem/build.gradle.kts
- core/network/build.gradle.kts
- core/webview/build.gradle.kts
- data/mypage/build.gradle.kts
- data/poke/build.gradle.kts
- data/soptamp/build.gradle.kts
- domain/build.gradle.kts
- domain/mypage/build.gradle.kts
- domain/poke/build.gradle.kts
- domain/soptamp/build.gradle.kts
- feature/auth/build.gradle.kts
- feature/mypage/build.gradle.kts
- feature/poke/build.gradle.kts
- feature/soptamp/build.gradle.kts
> [feature/pure-kotlin-plugin] Apply Pure Kotlin Plugin for build.gradle.kts

- .github/ISSUE_TEMPLATE/feature-issue-template.md
- 제목에 [Feat] 라는 헤더가 붙습니다.
- labels에 자동으로 enhancement가 붙도록 하였습니다.
> Feature 이슈 템플릿 생성

- app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
- app/src/main/java/org/sopt/official/feature/home/adapter/SmallBlockAdapter.kt
- core/auth/build.gradle.kts
- core/webview/build.gradle.kts
- core/webview/src/main/AndroidManifest.xml
- core/webview/src/main/java/org/sopt/official/webview/view/SoptWebViewClient.kt
- core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
- core/webview/src/main/res/layout/activity_web_view.xml
- core/webview/src/main/res/values/strings.xml
- domain/mypage/build.gradle.kts
- domain/poke/build.gradle.kts
- domain/soptamp/build.gradle.kts
- gradle/libs.versions.toml
https://github.com/sopt-makers/sopt-android/assets/108331578/e768c973-ded1-4116-92d2-9fd51cadbcfb
close #462
> [Feature/kdh/#462-web-view] 인앱 브라우저 구현

- app/src/main/java/org/sopt/official/domain/entity/attendance/AttendanceButtonType.kt
- app/src/main/java/org/sopt/official/feature/attendance/AttendanceViewModel.kt
- gradle/libs.versions.toml
1. 기존 AttendanceButtonType을 지정해주는 메서드가 정상적으로 동작하지 않음
2. "이미 종료된 세션입니다." 메시지가 핸들링되지 않음
3. ERROR를 핸들링하는 분기가 존재하지 않음
=> 해결 완료
> [hotfix/hide-button-after-attendance] 출석 뷰 버튼 버그 수정

- app/src/main/java/org/sopt/official/data/model/home/AppServiceResponse.kt
- app/src/main/java/org/sopt/official/data/repository/home/DefaultHomeRepository.kt
- app/src/main/java/org/sopt/official/data/service/home/HomeService.kt
- app/src/main/java/org/sopt/official/domain/entity/home/AppService.kt
- app/src/main/java/org/sopt/official/domain/repository/home/HomeRepository.kt
- app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
- app/src/main/java/org/sopt/official/feature/home/HomeViewModel.kt
- app/src/main/java/org/sopt/official/feature/home/model/AppServiceState.kt
- app/src/main/java/org/sopt/official/feature/home/model/AppServiceUiState.kt
- app/src/main/res/layout/activity_sopt_main.xml
- app/src/main/res/layout/item_main_poke.xml
- app/src/main/res/layout/item_main_soptamp.xml
- core/common/src/main/java/org/sopt/official/common/util/ContentUriRequestBody.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/component/button/SoptampButton.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/DatePicker.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/Header.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/Memo.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankNumber.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerList.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingScreen.kt
- closed #666 
date 값 검증
https://github.com/sopt-makers/sopt-android/assets/52882799/dee5b35f-3363-4431-8a93-296a54387525
> feat/#666 Soptamp qa + main fix

- gradle/libs.versions.toml
> [release/2.2.0] 🚨 2.2.0

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceActivity.kt
- app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceLoadingScreen.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceAction.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceUiState.kt
- gradle/libs.versions.toml
> Attendance screen compose setting

- core/designsystem/src/main/java/org/sopt/official/designsystem/Theme.kt
- core/designsystem/src/main/java/org/sopt/official/designsystem/Type.kt
> feat: add new typography

- .github/workflows/develop_PR_builder.yml
> [feature/apply-pr-target-in-action] Add pull_request_target trigger in PR Builder action

- feature/auth/src/main/java/org/sopt/official/auth/AuthIntentFactory.kt
- feature/auth/src/main/java/org/sopt/official/auth/Constants.kt
> [fix] chrome tab login issue

- .github/workflows/develop_PR_builder.yml
- .github/workflows/develop_merge_builder.yml
- .gitignore
- app/build.gradle.kts
- app/proguard-rules.pro
- app/src/main/AndroidManifest.xml
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/CommonConfigs.kt
- build.gradle.kts
- gradle/libs.versions.toml
- scripts/fecth_script.sh
- secrets.defaults.properties
> [feature/remove-sentry] Remove sentry

- README.md
- gradle/libs.versions.toml
> [feature/apply-kotlin-2020] Apply Kotlin 2.0.20

- app/src/release/generated/baselineProfiles/baseline-prof.txt
- app/src/release/generated/baselineProfiles/startup-prof.txt
- data/fortune/src/main/AndroidManifest.xml
- data/fortune/src/main/java/org/sopt/official/data/fortune/di/ApiModule.kt
- data/fortune/src/main/java/org/sopt/official/data/fortune/di/RepositoryModule.kt
- data/fortune/src/main/java/org/sopt/official/data/fortune/mapper/FortuneMapper.kt
- data/fortune/src/main/java/org/sopt/official/data/fortune/remote/api/FortuneApi.kt
- data/fortune/src/main/java/org/sopt/official/data/fortune/remote/response/TodayFortuneCardResponse.kt
- data/fortune/src/main/java/org/sopt/official/data/fortune/remote/response/TodayFortuneWordResponse.kt
- data/fortune/src/main/java/org/sopt/official/data/fortune/repository/DefaultFortuneRepository.kt
- domain/fortune/src/main/java/org/sopt/official/domain/fortune/model/TodayFortuneCard.kt
- domain/fortune/src/main/java/org/sopt/official/domain/fortune/model/TodayFortuneWord.kt
- domain/fortune/src/main/java/org/sopt/official/domain/fortune/repository/FortuneRepository.kt
- domain/fortune/src/main/java/org/sopt/official/domain/fortune/usecase/GetTodayDateUseCase.kt
- domain/fortune/src/main/java/org/sopt/official/domain/fortune/usecase/GetTodayFortuneUseCase.kt
- feature/fortune/src/androidTest/java/org/sopt/official/feature/fortune/fortuneDetail/FortuneDetailScreenTest.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/FortuneDetailRoute.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/FortuneDetailViewModel.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/FortuneDetailBox.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/component/TodayFortuneDashboard.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/feature/fortuneDetail/model/FortuneDetailUiState.kt
- feature/mypage/src/main/java/org/sopt/official/feature/mypage/component/MyPageSection.kt
> [Build/#869] baseline&spotless 적용

- core/network/src/debug/java/org/sopt/official/network/FlipperInitializer.kt
- close #919 
- 이슈 링크: https://github.com/sopt-makers/sopt-android/issues/919
> [feat/#919] SharedPreferences Debugger 추가

- .github/workflows/baseline-profile.yml
> Change baselineProfile.yml

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/sopt/official/deeplink/AppDeeplinkModule.kt
- app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
- app/src/main/java/org/sopt/official/feature/deeplink/DeepLinkSchemeActivity.kt
- app/src/main/java/org/sopt/official/feature/home/HomeActivity.kt
- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/org/sopt/official/plugin/DeeplinkPlugin.kt
- core/webview/build.gradle.kts
- core/webview/src/main/java/org/sopt/official/webview/deeplink/WebDeeplinkModule.kt
- core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
- feature/fortune/build.gradle.kts
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/FortuneActivity.kt
- feature/fortune/src/main/java/org/sopt/official/feature/fortune/deeplink/FortuneDeeplinkModule.kt
- gradle/libs.versions.toml
https://github.com/user-attachments/assets/1bf63f4b-c009-490f-abb5-d21549e5f592
> [#948] 주요 화면 DeepLink 처리

- gradle/libs.versions.toml
- https://github.com/google/dagger/issues/4451
- 이 이슈로 인해서 대거 다음 버전 나오지 않는 이상 코틀린 버전 올리기 어려울듯
- https://github.com/google/dagger/issues/4451
> Downgrade kotlin version

- README.md
- gradle/libs.versions.toml
> Update Kotlin 2.1.0

- core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
> [FIX] Null 설정 관련 수정

- app/src/main/java/org/sopt/official/data/AttendanceMapper.kt
- app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
- app/src/main/java/org/sopt/official/domain/entity/attendance/Attendance.kt
- app/src/main/java/org/sopt/official/feature/attendance/AttendanceMapper.kt
- app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceActivity.kt
- app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceCodeDialog.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceCodeDialog.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceProgressBar.kt
- app/src/main/java/org/sopt/official/feature/attendance/compose/component/MidtermAttendanceCard.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceAction.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceSession.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceUiState.kt
- app/src/main/java/org/sopt/official/feature/attendance/model/MidtermAttendance.kt
- core/designsystem/src/main/java/org/sopt/official/designsystem/Color.kt
> Open attendance dialog

- app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> [feature/home-navigation] HomeActivity -> MainActivity

- app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> HomeActivity -> MainActivity

- feature/home/src/main/java/org/sopt/official/feature/home/HomeRoute.kt
- feature/home/src/main/java/org/sopt/official/feature/home/NewHomeViewModel.kt
- feature/main/src/main/java/org/sopt/official/feature/main/MainNavigator.kt
- feature/main/src/main/java/org/sopt/official/feature/main/MainScreen.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
- feature/poke/src/main/java/org/sopt/official/feature/poke/notification/PokeNotificationActivity.kt
- feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptLogViewModel.kt
- feature/soptlog/src/main/java/org/sopt/official/feature/soptlog/SoptlogScreen.kt
> [FIX/#1128] 1차 전체 QA 사항 반영

- app/src/main/AndroidManifest.xml
> [HOTFIX/#1133] allowBackup false로 수정

- app/src/main/java/org/sopt/official/feature/navigator/NavigatorProviderIntent.kt
- app/src/main/java/org/sopt/official/feature/notification/SchemeActivity.kt
- core/common/src/main/java/org/sopt/official/common/navigator/DeepLinkType.kt
- core/common/src/main/java/org/sopt/official/common/navigator/NavigatorProvider.kt
> [FIX/#1135] update home intent to main intent in SchemeActivity

- core/security/src/main/java/org/sopt/official/security/util/CryptoExt.kt
- 근데 뭔가 재로그인을 해야할 것 같은데 왜 자동로그인이 될까요?
- 오류가 다 해결된게 맞을까요?
> [HOTFIX/#1137] bytearray 길이 검증

- data/mypage/src/main/java/org/sopt/official/data/mypage/model/request/UpdateProfileMessageRequest.kt
- data/mypage/src/main/java/org/sopt/official/data/mypage/model/response/UpdateProfileMessageResponse.kt
- data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/model/response/ModifyStampResponse.kt
- feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
- 난독화 문제로 인해 서버통신이 안 되고 있던 기능들 수정했습니다
- 추가로 편한 디버깅을 위해 서버 통신 실패 시 Timber가 찍히도록 추가해두었어요!
- 지속적으로 난독화 이슈가 생기고 있는데 시간 여유 있을 때 프로가드 룰을 점검해보는 것이 좋을 것 같아요
> [FIX/#1160] 솝탬프 관련 기능 난독화 문제 해결

- baselineprofile/build.gradle.kts
- gradle/libs.versions.toml
> Bump Kotlin 2.2.0

- .github/ISSUE_TEMPLATE/android_issue_template.md
- .github/PULL_REQUEST_TEMPLATE.md
- closed #1270 
- 템플릿 수정했어요
N/A
N/A
템플릿 드디어 수정 완료...ㅎㅎㅎ
> [DOCS/#1270] 깃허브 템플릿 수정

- app/src/main/java/org/sopt/official/feature/auth/utils/GoogleLoginManager.kt
- core/common/src/main/java/org/sopt/official/common/coroutines/runCatching.kt
- 특정 디바이스 환경에서 Credential API 로그인 안되는 이슈 수정
> [FIX] 로그인 에러 수정
